"""Внесення змін перед запуском в продакшн

Revision ID: 03c0ee0bfd31
Revises: a0fa0da988a3
Create Date: 2025-07-20 20:32:42.996983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c0ee0bfd31'
down_revision: Union[str, Sequence[str], None] = 'a0fa0da988a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('seen_items_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('seen_items_json')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
