"""Add max_participants to Event table

Revision ID: 13563c8841e5
Revises: ba1cfdc69d17
Create Date: 2025-10-13 02:27:03.900952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13563c8841e5'
down_revision: Union[str, Sequence[str], None] = 'ba1cfdc69d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))

    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_participant_event_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('event_participant_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('removed_participant_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('removed_participant_log_admin_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('removed_participant_log_event_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('removed_participant_log_removed_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['removed_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['admin_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('removed_participant_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('removed_participant_log_removed_user_id_fkey'), 'user', ['removed_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('removed_participant_log_event_id_fkey'), 'event', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('removed_participant_log_admin_id_fkey'), 'user', ['admin_id'], ['id'])

    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_participant_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('event_participant_event_id_fkey'), 'event', ['event_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
