"""Внесення змін перед запуском в продакшн

Revision ID: 6778924ed4e0
Revises: 209bd52e186a
Create Date: 2025-07-06 01:42:41.843530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6778924ed4e0'
down_revision: Union[str, Sequence[str], None] = '209bd52e186a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
