"""Generate single correct schema from live DB

Revision ID: 759ba9649036
Revises: 
Create Date: 2025-10-14 02:32:02.246410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759ba9649036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('participants_json')

    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_column('team_name')

    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.alter_column('logged_at',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)

    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('logged_at',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_fee_payment_date')
        batch_op.drop_column('has_paid_fees')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_paid_fees', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_fee_payment_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('logged_at',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('event_date',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.alter_column('logged_at',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants_json', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
