"""Add payment_period to FeeLog model

Revision ID: 830d4086a2d4
Revises: 6659da20cbcf
Create Date: 2025-07-02 19:58:55.935161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830d4086a2d4'
down_revision: Union[str, Sequence[str], None] = '6659da20cbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_period', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_log', schema=None) as batch_op:
        batch_op.drop_column('payment_period')

    # ### end Alembic commands ###
