"""Внесення змін перед запуском в продакшн

Revision ID: a0fa0da988a3
Revises: 6778924ed4e0
Create Date: 2025-07-06 02:14:04.855020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fa0da988a3'
down_revision: Union[str, Sequence[str], None] = '6778924ed4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fee_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('logged_by_admin', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('logged_at', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_period', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_log_pkey'))
    )
    # ### end Alembic commands ###
