"""Додано поле status до EventParticipant

Revision ID: ba1cfdc69d17
Revises: 3e123c79dd53
Create Date: 2025-10-13 01:03:50.223304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1cfdc69d17'
down_revision: Union[str, Sequence[str], None] = '3e123c79dd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
