"""Add game_log table and missing columns (last_fee_payment_date, image_url)

Revision ID: d92fa3babf12
Revises: a4c7626fcff8
Create Date: 2025-07-02 01:55:24.282108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92fa3babf12'
down_revision: Union[str, Sequence[str], None] = 'a4c7626fcff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.String(length=20), nullable=False),
    sa.Column('logged_at', sa.String(length=20), nullable=True),
    sa.Column('active_participants_json', sa.Text(), nullable=True),
    sa.Column('cancelled_participants_json', sa.Text(), nullable=True),
    sa.Column('teams_json', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_log')
    # ### end Alembic commands ###
